Pipeline

diff --git a/.github/workflows/test-flow.yml b/.github/workflows/test-flow.yml
--- a/.github/workflows/test-flow.yml
+++ b/.github/workflows/test-flow.yml
@@ -69,11 +69,8 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
       
-      - name: Add Known Hosts
-        run: |
-          ssh-keyscan -H 51.16.217.95 >> ~/.ssh/known_hosts || { echo "Failed to add host key"; exit 1; }
 
-      
+
       - name: Whitelist Runner IP
         run: |
           aws ec2 authorize-security-group-ingress \
@@ -81,7 +78,11 @@ jobs:
             --protocol tcp \
             --port 22 \
             --cidr ${{ steps.ip.outputs.ipv4 }}/32
-      
+
+      - name: Add Known Hosts
+        run: |
+          ssh-keyscan -H 51.16.217.95 >> ~/.ssh/known_hosts || { echo "Failed to add host key"; exit 1; }
+
       - name: Execute Remote SSH Commands
         run: |
           ssh ubuntu@51.16.217.95 "echo Hello World"
