Pipeline

diff --git a/.github/workflows/test-flow.yml b/.github/workflows/test-flow.yml
--- a/.github/workflows/test-flow.yml
+++ b/.github/workflows/test-flow.yml
@@ -71,7 +71,7 @@ jobs:
       
       - name: Add Known Hosts
         run: |
-          ssh-keyscan -H 51.16.217.95 >> ~/.ssh/known_hosts || {
+          ssh-keyscan -H 51.16.217.95 >> ~/.ssh/known_hosts || { echo "Failed to add host key"; exit 1; }
 
       
       - name: Whitelist Runner IP
@@ -84,7 +84,7 @@ jobs:
       
       - name: Execute Remote SSH Commands
         run: |
-          ssh ${{ secrets.EC2_USER }}@51.16.217.95 "echo Hello World"
+          ssh ubuntu@51.16.217.95 "echo Hello World"
       
       - name: Remove Runner IP
         if: always()
